<?php 
$historics = $viewData['historics'];

?>
<h1 class="page-header">Missions</h1>

<a href="/Mission/insert">Insert</a>
<div class="table-responsive">
<table class="table table-striped">
    <?php foreach($historics as $id => $value):?>
        <tr>
           <?php 
            foreach ($value as $id2 => $value2):
            
                if($id2<>'idhistoric')
                {
                ?>   
                    <td><?php echo $value2;
                }    
                ?></td>
            <?php endforeach; ?>
          <!--   <td>
                <a href="/Mission/update/id/<?=$historics[$id]['idhistoric'];?>">Update</a> | 
                <a href="/Mission/delete/id/<?=$historics[$id]['idhistoric'];?>">Delete</a>
            </td> -->
        </tr>
    <?php endforeach; ?>
</table>
</div>