<?php 
$data = $viewData['fieldsLine'][0];

include (VENDOR_PATH.'/acl/Core/src/Core/Forms/RenderForm.php');
$formDefinition = include (APPLICATION_PATH.'/src/Character/Form/CharacterForm.php');
// $data = array();    //initialize the data as a array
$userFieldsIndex = 0;
          //  die;

// foreach ($fieldsLine as $fieldName => $fieldAttributes)
// {
//     $valuesField = $fieldsLine[$fieldName];
//     $data[$fieldName] = $valuesField;
//    // $userFieldsIndex = $userFieldsIndex + 1;
// }            
            

// foreach ($formDefinition as $fieldName => $fieldAttributes)
// {
//     $valuesField = $fieldsLine[$fieldName];
//     $data[$fieldName] = $valuesField;
//     $userFieldsIndex = $userFieldsIndex + 1;
// }

$data['id'] = $data['idcharacter'];
//$data['id'] = $data['class_idclass'];



// echo "<pre> formdefinition";
// print_r($fieldsLine);
// echo "</pre>";

// echo "<pre> data";
// print_r($data);
// echo "</pre>";

echo(renderForm($formDefinition, '/Character/update', 'post', $data));