<?php 
$datas = $viewData['characters'];

?>
<h1 class="page-header">Personajes</h1>

<a href="/Character">Crear Personaje</a>
<div class="table-responsive">
<table class="table table-striped">
    <?php foreach($datas as $id => $data):?>
        <tr>
           <?php 
            foreach ($data as $key => $value):?>               
                <td><?php 
                if ($key<>'idcharacter')
                {
                    echo $value;
                }
                ?></td>
            <?php endforeach; ?>
            <td>
                <a href="/Character/update/idcharacter/<?=$data['idcharacter'];?>">Update</a> | 
                <a href="/Character/delete/idcharacter/<?=$data['idcharacter'];?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
</div>